"""initial schema

Revision ID: 4d1d32d9239d
Revises: 
Create Date: 2025-05-20 18:36:31.678862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1d32d9239d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('github_username', sa.String(length=128), nullable=True),
    sa.Column('encrypted_github_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_table('build',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=True),
    sa.Column('repo_url', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('build_command', sa.String(length=255), nullable=True),
    sa.Column('output_dir', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('app_url', sa.String(length=255), nullable=True),
    sa.Column('auto_deploy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build')
    op.drop_table('user')
    # ### end Alembic commands ###
