"""add site object ID to build

Revision ID: 7b272395ea1b
Revises: 4d1d32d9239d
Create Date: 2025-05-21 15:43:07.260933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b272395ea1b'
down_revision = '4d1d32d9239d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_object_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_column('site_object_id')

    # ### end Alembic commands ###
