"""Rename slug to blob_id in Function

Revision ID: 8a3a68f74c84
Revises: a0205f0d7e13
Create Date: 2025-05-22 11:14:36.295185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3a68f74c84'
down_revision = 'a0205f0d7e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blod_id', sa.String(length=128), nullable=True))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('blod_id')

    # ### end Alembic commands ###
